#!/bin/sh

################################################################################
# Specify the filepath of the verilog library file of standard cell
################################################################################
VERILOG_LIB=/afs/ee.ust.hk/staff/ee/dept/public/eesm6980/digital/GSCLib3/verilog/GSCLib_3.0.v

SDF_LOCATION="../syn/results/manchester_dec.mapped.sdf"

vcs -full64 ../syn/results/manchester_dec.mapped.v ../tb/manchester_dec_tb.v +v2k -debug_all -top manchester_dec_tb \
  -timescale=1ns/1ps +neg_tchk +warn=noTFIPC -v $VERILOG_LIB +define+SDF_FILE=\"$SDF_LOCATION\"