#!/bin/sh

################################################################################
# Specify the filepath of the verilog library file of standard cell
################################################################################
#VERILOG_LIB=/afs/ee.ust.hk/staff/ee/dept/public/eesm6980/digital/GSCLib3/verilog/GSCLib_3.0.v

#SDF_LOCATION="../layout/results/encoder.sdf"

vcs -full64 ../layout/results/encoder.routed.v ../tb/encoder_tb.v +v2k -debug_all -top encoder_tb \
  -timescale=1ns/1ps +neg_tchk +warn=noTFIPC,noSDFCOM_UHICD -v /afs/ee.ust.hk/staff/ee/dept/public/eesm6980/digital/GSCLib3/verilog/GSCLib_3.0.v +define+SDF_FILE=\"../layout/results/encoder.sdf\"
